#!/usr/bin/env python3
"""Regenerate examples/examples.md from real `greatspectate` output
against the spec/source files in this directory. Run via `make
examples` -- examples.md is generated, never hand-edited.
"""

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
COVERAGE = ROOT / ".coverage"

LANGUAGES = [
    {
        "name": "Python",
        "file": "src/tale.py",
        "fence_lang": "python",
        "flags": [],
        "display_flags": "",
    },
    {
        "name": "C++",
        "file": "src/tale.cpp",
        "fence_lang": "cpp",
        "flags": ["--comment-start", "// ", "--comment-continue", "//"],
        "display_flags": "--comment-start '// ' --comment-continue '//' ",
    },
    {
        "name": "Rust",
        "file": "src/tale.rs",
        "fence_lang": "rust",
        "flags": [
            "--comment-start", "/* ", "--comment-continue", "*", "--comment-end", "*/",
        ],
        "display_flags": (
            "--comment-start '/* ' --comment-continue '*' --comment-end '*/' "
        ),
    },
]


def run(args):
    """Run greatspectate, with stderr interleaved into stdout in real
    chronological order (rather than captured separately) so e.g. a
    failing quote shows up in file order relative to passing ones, not
    shoved to the end.
    """
    return subprocess.run(
        [sys.executable, "-m", "greatspectations", *args],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, cwd=ROOT,
    )


def fence(text, lang=""):
    return "```{}\n{}\n```".format(lang, text.rstrip("\n"))


def console(command, output):
    return "```console\n$ {}\n{}\n```".format(command, output.rstrip("\n"))


def main():
    COVERAGE.unlink(missing_ok=True)

    lang_sections = []
    for lang in LANGUAGES:
        source_code = (ROOT / lang["file"]).read_text()
        result = run([
            "check", "--config", "specquotes.toml", "--coverage", ".coverage",
            "-v", "-k", *lang["flags"], lang["file"],
        ])
        output = result.stdout.rstrip("\n")
        display_cmd = (
            "greatspectate check --config specquotes.toml --coverage .coverage "
            "-v -k {}{}".format(lang["display_flags"], lang["file"])
        )
        lang_sections.append({
            "name": lang["name"], "fence_lang": lang["fence_lang"],
            "source": source_code, "display_cmd": display_cmd, "output": output,
            "ok": result.returncode == 0,
        })

    coverage_result = run([
        "coverage", "--config", "specquotes.toml", "--coverage", ".coverage",
        "--source", "dickens:1",
    ])
    coverage_output = coverage_result.stdout.rstrip("\n")

    spec_text = (ROOT / "spec" / "01-the-period.md").read_text()

    (ROOT / "examples.md").write_text(render(lang_sections, coverage_output, spec_text))
    COVERAGE.unlink(missing_ok=True)
    print("wrote", ROOT / "examples.md")


def render(lang_sections, coverage_output, spec_text):
    parts = [
        "# Great Spectations, worked example",
        "",
        "Generated by `examples/generate.py` (via `make examples`) from real "
        "`greatspectate` output against the files in this directory -- don't "
        "hand-edit this file, it will be overwritten.",
        "",
        "The \"spec\" here is the famous opening paragraph of Dickens'"
        " *A Tale of Two Cities* (public domain) -- chosen because it has "
        "nothing to do with software, which is the point: `greatspectate` "
        "checks a quote against *any* text source, not just RFCs and "
        "protocol specs. All three source files below share one coverage "
        "file (`--coverage .coverage`), built up across the three `check` "
        "runs.",
        "",
        "## The spec",
        "",
        fence(spec_text, "markdown"),
        "",
    ]

    for sec in lang_sections:
        verdict = "passes" if sec["ok"] else "**fails**"
        parts += [
            "## {}".format(sec["name"]),
            "",
            fence(sec["source"], sec["fence_lang"]),
            "",
            "This {}:".format(verdict),
            "",
            console(sec["display_cmd"], sec["output"]),
            "",
        ]

    parts += [
        "## Coverage",
        "",
        "`greatspectate coverage` annotates the whole spec: `+`/`++`/`+++` "
        "for a line quoted 1/2/3-or-more times across the three files above, "
        "`***` for a line that's supposed to be quoted (named in `normative` "
        "-- see `specquotes.toml`) but isn't, and a blank prefix for "
        "ordinary prose that isn't expected to be quoted at all.",
        "",
        console(
            "greatspectate coverage --config specquotes.toml --coverage "
            ".coverage --source dickens:1",
            coverage_output,
        ),
        "",
        "Two gaps show up, for two different reasons: the opening line was "
        "*attempted* (Rust's \"blurst of times\") but the quote is wrong, so "
        "it never matched anything; the \"Light\"/\"Darkness\" line was never "
        "quoted by anyone at all. `check` catches the first kind immediately "
        "-- `coverage` is what catches the second.",
        "",
    ]
    return "\n".join(parts)


if __name__ == "__main__":
    main()
