#!/usr/bin/env python3
"""Regenerate examples/examples.md, the worked-example tabs in
web/index.html, and the closest-match example in ../README.md, from
real `greatspectate` output against the spec/source files in this
directory. Run via `make examples` -- examples.md and the marked
blocks in index.html/README.md are never hand-edited, all get
overwritten.
"""

import html
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
WEB_INDEX = ROOT.parent / "web" / "index.html"
README = ROOT.parent / "README.md"
COVERAGE = ROOT / ".coverage"

# The absolute path config.py resolves 'dir = "spec"' to is specific to
# whatever machine generated this -- replace it with a clean relative
# form before either generated doc is written.
SPEC_DIR_PREFIX = str(ROOT / "spec") + "/"

LANGUAGES = [
    {
        "name": "Python",
        "tab": "python",
        "file": "src/tale.py",
        "fence_lang": "python",
        "flags": [],
        "display_flags": "",
    },
    {
        "name": "Rust",
        "tab": "rust",
        "file": "src/tale.rs",
        "fence_lang": "rust",
        "flags": ["--comment-start", "// ", "--comment-continue", "//"],
        "display_flags": "--comment-start '// ' --comment-continue '//' ",
    },
]


def run(args):
    """Run greatspectate, with stderr interleaved into stdout in real
    chronological order (rather than captured separately) so e.g. a
    failing quote shows up in file order relative to passing ones, not
    shoved to the end.
    """
    return subprocess.run(
        [sys.executable, "-m", "greatspectations", *args],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, cwd=ROOT,
    )


def clean_paths(text):
    return text.replace(SPEC_DIR_PREFIX, "")


def fence(text, lang=""):
    return "```{}\n{}\n```".format(lang, text.rstrip("\n"))


def console(command, output):
    return "```console\n$ {}\n{}\n```".format(command, output.rstrip("\n"))


def main():
    COVERAGE.unlink(missing_ok=True)

    lang_sections = []
    for lang in LANGUAGES:
        source_code = (ROOT / lang["file"]).read_text()
        result = run([
            "check", "--config", "specquotes.toml", "--coverage", ".coverage",
            "-v", "-k", *lang["flags"], lang["file"],
        ])
        output = clean_paths(result.stdout.rstrip("\n"))
        display_cmd = (
            "greatspectate check --config specquotes.toml --coverage .coverage "
            "-v -k {}{}".format(lang["display_flags"], lang["file"])
        )
        lang_sections.append({
            **lang, "source": source_code, "display_cmd": display_cmd,
            "output": output, "ok": result.returncode == 0,
        })

    coverage_result = run([
        "coverage", "--config", "specquotes.toml", "--coverage", ".coverage",
        "--source", "dickens:1",
    ])
    coverage_output = clean_paths(coverage_result.stdout.rstrip("\n"))

    spec_text = (ROOT / "spec" / "01-the-period.md").read_text()

    (ROOT / "examples.md").write_text(
        render_markdown(lang_sections, coverage_output, spec_text)
    )
    print("wrote", ROOT / "examples.md")

    inject_marked_block(
        WEB_INDEX, WEB_BEGIN_MARKER, WEB_END_MARKER,
        render_web_fragment(lang_sections, coverage_output),
    )
    print("updated", WEB_INDEX)

    note = note_example(lang_sections)
    if note is not None:
        inject_marked_block(README, README_BEGIN_MARKER, README_END_MARKER, note)
        print("updated", README)

    COVERAGE.unlink(missing_ok=True)


def render_markdown(lang_sections, coverage_output, spec_text):
    parts = [
        "# Great Spectations, worked example",
        "",
        "Generated by `examples/generate.py` (via `make examples`) from real "
        "`greatspectate` output against the files in this directory -- don't "
        "hand-edit this file, it will be overwritten.",
        "",
        "The \"spec\" here is the famous opening paragraph of Dickens'"
        " *A Tale of Two Cities* (public domain) -- chosen because it has "
        "nothing to do with software, which is the point: `greatspectate` "
        "checks a quote against *any* text source, not just RFCs and "
        "protocol specs. All three source files below share one coverage "
        "file (`--coverage .coverage`), built up across the three `check` "
        "runs.",
        "",
        "## The spec",
        "",
        fence(spec_text, "markdown"),
        "",
    ]

    for sec in lang_sections:
        verdict = "passes" if sec["ok"] else "**fails**"
        parts += [
            "## {}".format(sec["name"]),
            "",
            fence(sec["source"], sec["fence_lang"]),
            "",
            "This {}:".format(verdict),
            "",
            console(sec["display_cmd"], sec["output"]),
            "",
        ]

    parts += [
        "## Coverage",
        "",
        "`greatspectate coverage` annotates the whole spec: `+`/`++`/`+++` "
        "for a line quoted 1/2/3-or-more times across the three files above, "
        "`***` for a line that's supposed to be quoted (named in `normative` "
        "-- see `specquotes.toml`) but isn't, and a blank prefix for "
        "ordinary prose that isn't expected to be quoted at all.",
        "",
        console(
            "greatspectate coverage --config specquotes.toml --coverage "
            ".coverage --source dickens:1",
            coverage_output,
        ),
        "",
        "Two gaps show up, for two different reasons: the opening line was "
        "*attempted* (Rust's \"blurst of times\") but the quote is wrong, so "
        "it never matched anything; the \"Light\"/\"Darkness\" line was never "
        "quoted by anyone at all. `check` catches the first kind immediately "
        "-- `coverage` is what catches the second.",
        "",
    ]
    return "\n".join(parts)


def _esc(text):
    return html.escape(text, quote=False)


def _tab_button(lang, selected):
    return '<button role="tab" aria-selected="{}" data-tab="{}">{}</button>'.format(
        "true" if selected else "false", lang["tab"], _esc(lang["name"])
    )


def _cmd_output_html(output):
    """Color a captured check/coverage command's output line-by-line:
    a 'cannot find match' failure line stands out, everything else is
    plain -- mirrors how the terminal output actually reads.
    """
    lines = []
    for line in output.splitlines():
        cls = "cmd-fail" if "cannot find match" in line else "cmd-line"
        lines.append('<span class="{}">{}</span>'.format(cls, _esc(line)))
    return "\n".join(lines)


def _lang_panel(sec, selected):
    verdict_cls = "ok" if sec["ok"] else "fail"
    verdict = "all quotes match" if sec["ok"] else "one quote doesn't match"
    return "\n".join([
        '<div class="tab-panel" data-tab-panel="{}"{}>'.format(
            sec["tab"], "" if selected else " hidden"
        ),
        '<pre class="src"><code>{}</code></pre>'.format(_esc(sec["source"])),
        '<p class="result-chip {}"><span class="dot" aria-hidden="true"></span>'
        '<span class="msg"><strong>greatspectate check</strong> &mdash; '
        '{}</span></p>'.format(verdict_cls, verdict),
        '<pre class="cmd-output"><code>$ {}\n{}</code></pre>'.format(
            _esc(sec["display_cmd"]), _cmd_output_html(sec["output"])
        ),
        '</div>',
    ])


def _coverage_panel(coverage_output, selected):
    lines = []
    for line in coverage_output.splitlines():
        prefix, _, rest = line.partition(" ")
        if prefix == "***":
            cls = "cov-gap"
        elif prefix.startswith("+"):
            cls = "cov-covered"
        else:
            cls = "cov-neutral"
            prefix = "   "  # partition() only ate one of the 3 prefix spaces
            rest = line.strip()
        lines.append('<span class="{}">{} {}</span>'.format(cls, prefix, _esc(rest)))
    return "\n".join([
        '<div class="tab-panel" data-tab-panel="coverage"{}>'.format(
            "" if selected else " hidden"
        ),
        '<pre class="cov"><code>{}</code></pre>'.format("\n".join(lines)),
        '</div>',
    ])


def render_web_fragment(lang_sections, coverage_output):
    tabs = [_tab_button(sec, i == 0) for i, sec in enumerate(lang_sections)]
    tabs.append(
        '<button role="tab" aria-selected="false" data-tab="coverage">Coverage</button>'
    )
    panels = [_lang_panel(sec, i == 0) for i, sec in enumerate(lang_sections)]
    panels.append(_coverage_panel(coverage_output, False))

    return "\n".join([
        '<div class="example-tabs" id="worked-example-tabs">',
        '<div class="panel-head">',
        '<div class="tab-list" role="tablist" aria-label="Language / coverage">',
        *tabs,
        '</div>',
        '</div>',
        *panels,
        '</div>',
    ])


def inject_marked_block(path, begin_marker, end_marker, content):
    """Replace the text strictly between begin_marker and end_marker in
    path with content, leaving the markers and everything outside them
    untouched. Raises if the markers aren't found, in order.
    """
    text = path.read_text()
    start = text.index(begin_marker) + len(begin_marker)
    end = text.index(end_marker)
    if start > end:
        raise ValueError(
            "BEGIN/END markers out of order in {}: {!r} / {!r}".format(
                path, begin_marker, end_marker
            )
        )
    path.write_text(text[:start] + "\n" + content + "\n" + text[end:])


WEB_BEGIN_MARKER = "<!-- BEGIN GENERATED EXAMPLE (examples/generate.py -- do not hand-edit) -->"
WEB_END_MARKER = "<!-- END GENERATED EXAMPLE -->"

README_BEGIN_MARKER = "<!-- BEGIN GENERATED NOTE EXAMPLE (examples/generate.py -- do not hand-edit) -->"
README_END_MARKER = "<!-- END GENERATED NOTE EXAMPLE -->"


def note_example(lang_sections):
    """The 'cannot find match' + 'note: closest match' line pair from
    whichever language section actually failed with a note attached, for
    the README's example -- pulled from real output, not hand-typed.
    """
    for sec in lang_sections:
        lines = sec["output"].splitlines()
        for i, line in enumerate(lines):
            if "cannot find match" in line and i + 1 < len(lines) and " note: " in lines[i + 1]:
                return fence("\n".join([line, lines[i + 1]]))
    return None


if __name__ == "__main__":
    main()
